### ISSUE TITLE
Bug when using the Dataset Manager Advanced Dataset Search "Filter" functionality

### ISSUE THREAD

**Issue by ddelvecchio** [ddelvecchio/emf#8]
EPA's emf doesn't have this issue.

To recreate issue:

1.  Login into MARAMA's emf
2.  Go to the Adanced Dataset Search window of Dataset Manager
3.  Choose "Flat File 2010 Point" dataset type
4.  Type in filter:  SCC in ('10200101', '10200104')
5.  Run search.

Here is the exception from MARAMA's EMF tomcat server log file:

28 May 2014 18:09:36,077 ERROR DataServiceImpl:1650 - Could not find similar datasets.
java.sql.SQLException: Error with Data Value Filter, incorrect filter SQL syntax: SCC in ('10200101', '10200104')
               at gov.epa.emissions.framework.services.data.DatasetDAO.filter(DatasetDAO.java:1825)
               at gov.epa.emissions.framework.services.data.DatasetDAO.findSimilarDatasets(DatasetDAO.java:1794)
               at gov.epa.emissions.framework.services.data.DataServiceImpl.findDatasets(DataServiceImpl.java:1647)
               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
               at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
               at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
               at java.lang.reflect.Method.invoke(Unknown Source)
               at org.apache.axis.providers.java.RPCProvider.invokeMethod(RPCProvider.java:397)
               at org.apache.axis.providers.java.RPCProvider.processMessage(RPCProvider.java:186)
               at org.apache.axis.providers.java.JavaProvider.invoke(JavaProvider.java:323)
               at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
               at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
               at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
               at org.apache.axis.handlers.soap.SOAPService.invoke(SOAPService.java:454)
               at org.apache.axis.server.AxisServer.invoke(AxisServer.java:281)
               at org.apache.axis.transport.http.AxisServlet.doPost(AxisServlet.java:699)
               at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
               at org.apache.axis.transport.http.AxisServletBase.service(AxisServletBase.java:327)
               at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
               at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
               at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
               at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
               at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
               at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
               at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
               at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
               at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
               at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:409)
               at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1044)
               at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
               at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2441)
               at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2430)
               at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
               at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
               at java.lang.Thread.run(Unknown Source)

**Comment by cseppan** [comment]
Fixed in commit a947dd00b61715cfbd4c014067fcf2d66169d398
